##################################################################################
#       _            _
#      | |          | |
#    __| | ___   ___| | _____ _ __    ___ ___  _ __ ___  _ __   ___  ___  ___
#   / _` |/ _ \ / __| |/ / _ \ '__|  / __/ _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \
#  | (_| | (_) | (__|   <  __/ |    | (_| (_) | | | | | | |_) | (_) \__ \  __/
#   \__,_|\___/ \___|_|\_\___|_|     \___\___/|_| |_| |_| .__/ \___/|___/\___|
#                                                       | |
#                                                       |_|
##################################################################################
version: "3.0"
# docker compose up -d
services:

  ##################################################################################
  # rclone web gui
  ##################################################################################
#  rclone_rclone:
#    image: rclone/rclone
#    container_name: rclone_rclone
#    restart: always
#    command: rcd --rc-web-gui --rc-addr :${PORT_RCLONE_GUI} --rc-user ${RCLONE_USERNAME} --rc-pass ${RCLONE_PASSWORD}
#    ports:
#      - "${PORT_RCLONE_GUI}:${PORT_RCLONE_GUI}"
#    volumes:
#      - ${VOL_RCLONE_CONFIG_PATH}:/config/rclone
#      - ${VOL_RCLONE_CONFIG_PATH}:/logs
#    environment:
#      - PHP_TZ=${ENV_TIMEZONE}
#      - PUID=${ENV_PUID}
#      - PGID=${ENV_PUID}

  ##################################################################################
  # Influxdb
  ##################################################################################
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      INFLUXD_REPORTING_DISABLED: 'true'
      INFLUXD_HTTP_BIND_ADDRESS: ':8086'
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    stdin_open: true
    tty: true
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

##########################################################################
# Volumes
##########################################################################
volumes:
  influxdb_data: {}